# AlertManager configuration for SyncCash Orchestrator
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@synccash.com'
  smtp_auth_username: 'alerts@synccash.com'
  smtp_auth_password: 'your-smtp-password'

# The directory from which notification templates are read.
templates:
- '/etc/alertmanager/templates/*.tmpl'

# The root route on which each incoming alert enters.
route:
  # The labels by which incoming alerts are grouped together.
  group_by: ['alertname', 'service']
  
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  group_wait: 10s
  
  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 10s
  
  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 1h
  
  # A default receiver
  receiver: web.hook
  
  # All the above attributes are inherited by all child routes and can
  # overwritten on each.
  routes:
  # Critical alerts - immediate notification
  - match:
      severity: critical
    receiver: critical-alerts
    group_wait: 0s
    group_interval: 5s
    repeat_interval: 30m
    
  # Warning alerts - less frequent notifications
  - match:
      severity: warning
    receiver: warning-alerts
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 2h
    
  # Info alerts - daily digest
  - match:
      severity: info
    receiver: info-alerts
    group_wait: 5m
    group_interval: 1h
    repeat_interval: 24h

# Inhibition rules allow to mute a set of alerts given that another alert is firing.
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'service']

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

# Critical alerts - multiple notification channels
- name: 'critical-alerts'
  email_configs:
  - to: 'devops@synccash.com'
    subject: '🚨 CRITICAL: SyncCash Orchestrator Alert'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Service: {{ .GroupLabels.service }}
      Severity: {{ .CommonLabels.severity }}
      
      {{ range .Alerts }}
      Summary: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}
      
      Dashboard: http://localhost:3000/d/synccash-orchestrator
      
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    channel: '#alerts-critical'
    title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
    text: |
      *Service:* {{ .GroupLabels.service }}
      *Severity:* {{ .CommonLabels.severity }}
      {{ range .Alerts }}
      *Summary:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      {{ end }}
    
  webhook_configs:
  - url: 'http://localhost:8000/api/v1/alerts/webhook'
    send_resolved: true

# Warning alerts
- name: 'warning-alerts'
  email_configs:
  - to: 'devops@synccash.com'
    subject: '⚠️ WARNING: SyncCash Orchestrator Alert'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Service: {{ .GroupLabels.service }}
      Severity: {{ .CommonLabels.severity }}
      
      {{ range .Alerts }}
      Summary: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}
      
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    channel: '#alerts-warning'
    title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
    text: |
      *Service:* {{ .GroupLabels.service }}
      {{ range .Alerts }}
      *Summary:* {{ .Annotations.summary }}
      {{ end }}

# Info alerts - digest format
- name: 'info-alerts'
  email_configs:
  - to: 'devops@synccash.com'
    subject: 'ℹ️ INFO: SyncCash Orchestrator Daily Digest'
    body: |
      Daily Alert Digest for SyncCash Orchestrator
      
      {{ range .Alerts }}
      - {{ .Annotations.summary }}
      {{ end }}
