import { serve } from "@hono/node-server";
import { Hono } from "hono";
import dotenv from "dotenv";

dotenv.config();

// TODOS:
/**
 * 1. Set up this notifications service webhooks with kafka and redis to keep track of 
 *    transaction and payment status.
 * 2. Set up hooks and authenticated route to allow for users
 *    (users to be able to hook into service to check for status from other services)
 * 
 * Sorry, spent soo much time on slop code generated by AI from my team mates that I couldn't get any real work done here :(
 */
const app = new Hono();

app.get("/health", (c) => c.json({message: "Success... all is good here"}, 200));

serve({ 
  fetch: app.fetch,
  port: Number(process.env.PORT) || 8040
}, (info) => {
  console.log(`Server running on http://localhost:${info.port}`);
});
