global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # SyncCash Orchestrator Service
  - job_name: 'synccash-orchestrator'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:9100']

  # Notifications Service
  - job_name: 'notifications'
    static_configs:
      - targets: ['notifications:9100']

  # Fraud Detection Service
  - job_name: 'fraud-detection'
    static_configs:
      - targets: ['fraud-detection:9100']

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
